Sleep 1.5s
Type "cls"
Enter
Sleep 4s
Type "chmod +x lau"
Tab
Enter
Sleep 2.5s
Type "./laun"
Tab
Enter
Sleep 1.5s
Type "F"
Sleep 500ms
Enter
Sleep 1.5s
Type "q"
Enter
Sleep 2.5s
Type "./"
Sleep 2s
Type "lau"
Tab
Enter
Sleep 1s
Type "Q"
Backspace
Type "S"
Enter
Sleep 500ms
Type "S"
Enter
Sleep 1.5s
Type "telnet.s"
Sleep 1.5s
Backspace 2
Enter
Sleep 1s
Type "E"
Enter
Sleep 1s
Type "3310"
Sleep 5s
Type "./lau"
Tab
Enter
Sleep 2.5s
Type "Q"
Sleep 500ms
Backspace
Type "S"
Enter
Sleep 1s
Type "D"
Enter
Sleep 2s
Type "https://"
Sleep 2s
Type "github"
Sleep 500ms
Type "."
Sleep 500ms
Type "com/FBDev"
Sleep 1.5s
Type "/"
Sleep 7s
Enter
Sleep 2s
Type "test"
Enter
Sleep 10s
Type "c"
Sleep 500ms

